ARG FREEBSD_RELEASE
ARG PYTHON_VERSION

FROM ghcr.io/appjail-makejails/python:${FREEBSD_RELEASE}-${PYTHON_VERSION} AS python-builder

ARG YUBAL_VERSION

RUN pkg update && \
    pkg install -y FreeBSD-set-base-jail rust uv git-tiny && \
    install -d -m 755 /usr/local/sbin && \
    pkg clean -a && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

WORKDIR /src

RUN fetch https://github.com/guillevc/yubal/archive/refs/tags/v${YUBAL_VERSION}.tar.gz && \
    tar --strip-components=1 -xf v${YUBAL_VERSION}.tar.gz && \
    (cd packages/yubal && uv remove numpy) && \
    uv sync --package yubal-api --no-dev --frozen --no-editable && \
    rm -f v${YUBAL_VERSION}.tar.gz

FROM ghcr.io/appjail-makejails/python:${FREEBSD_RELEASE}-${PYTHON_VERSION}

ARG YUBAL_VERSION
ARG PYTHON_VERSION

LABEL org.opencontainers.image.title="Yubal" \
    org.opencontainers.image.description="Self-hosted YouTube Music downloader" \
    org.opencontainers.image.source="https://github.com/AppJail-makejails/yubal" \
    org.opencontainers.image.url="https://github.com/AppJail-makejails/yubal" \
    org.opencontainers.image.vendor="DtxdF" \
    org.opencontainers.image.authors="Jesús Daniel Colmenares Oviedo <dtxdf@disroot.org>"

RUN pkg update && \
    pkg install -y py${PYTHON_VERSION}-sqlite3 rsgain ffmpeg && \
    install -d -m 755 /usr/local/sbin && \
    pkg clean -a && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

WORKDIR /app

COPY web/yubal-v${YUBAL_VERSION}.frontend.tar.gz ./yubal.frontend.tar.gz

RUN mkdir -p web/dist && \
    tar -C web/dist --strip-components=1 -xf yubal.frontend.tar.gz && \
    rm -f yubal.frontend.tar.gz && \
    chown -R nobody:nobody web/dist

COPY --from=python-builder --chown=nobody:nobody /src/.venv .venv

RUN chown nobody:nobody /app /app/web /app/web/dist

ENV PATH="/app/.venv/bin:${PATH}" \
    PYTHONUNBUFFERED=1 \
    YUBAL_ROOT=/app \
    YUBAL_HOST=0.0.0.0 \
    YUBAL_PORT=8000

USER nobody
EXPOSE 8000
ENTRYPOINT ["python", "-m", "yubal_api"]
