build:
  variants:
    - tag: 15.0
      containerfile: Containerfile.pkg
      aliases: ["latest"]
      default: true
      args:
        FREEBSD_RELEASE: "15.0"
        PYTHON_VERSION: "312"
        YUBAL_VERSION: "0.7.2"
